# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160521_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='resource',
        ),
        migrations.AddField(
            model_name='resource',
            name='relationship',
            field=models.ManyToManyField(to='contacts.Relationship'),
        ),
    ]
